### ISSUE TITLE
Perf issues on few C extensions founded by Envato

### ISSUE THREAD

**Issue by benoittgt** [ASoftCo/leaky-gems#10]
Hello
Few gems are mentionned on [this blog post](http://webuild.envato.com/blog/tracking-down-ruby-heap-corruption/) by Envato : 
- https://github.com/xml4r/libxml-ruby/pull/119
- https://github.com/flori/json/pull/263

What do you think about them ? Should I add them when to the Readme when they will be merged ?

**Comment by benoittgt** [comment]
Ok https://github.com/xml4r/libxml-ruby/pull/119 has just been merged.

**Comment by sergey-alekseev** [comment]
Hi @benoittgt. I'm on a vacation. Will look into it in 10 days.

**Comment by sergey-alekseev** [comment]
`libxml-ruby` was merged in https://github.com/ASoftCo/leaky-gems/pull/11. Also I've just changed it's version to [< 2.9.0](https://github.com/ASoftCo/leaky-gems/commit/2952a697aab6e1b4a49502b506ef9b83fb0d8d71) as it's the correct one in my view.
I'm not sure about https://github.com/flori/json/pull/263.
So closing this issue.
