### ISSUE TITLE
Current link to Sequel issue

### ISSUE THREAD

**Issue by mizalewski** [ASoftCo/leaky-gems#14]
Hi,

I just read linked issue for Sequel and person, which create it was using Sequel API in wrong way.
After some discussion they agreed about what was happend in his situation (behavior was expected) and how he should use API.

He also created pull request (already merged to docs) with information about using this API (for connect to database without pooling).

I think Sequel should be removed from list.

**Comment by sergey-alekseev** [comment]
@mizalewski is it still actual?

**Comment by mizalewski** [comment]
No :) I just no read information in pull  request #9 on your repo before I created the issue.
