### ISSUE TITLE
Different types of memory issues

### ISSUE THREAD

**Issue by stereobooster** [ASoftCo/leaky-gems#15]
There different types of memory issues from my POV:
- memory leak which happens in C space - in extension or ruby implementation itself. Ruby is GCed so cannot see how you get memory leak in Ruby
- memory bloat - when objects allocated and reference stored in global space, so they never can be GCed. Typically happens in memoization.
- Useless gems. When useless gems loaded in application, so they take space, but do nothing.

And others, for which I haven't got a name. The question is: Is this repo appropriate for third type of issues?

Useless gems:
- https://github.com/RubyMoney/money/issues/688
- https://github.com/rack/rack-contrib/pull/114

Memory bloat:
- https://github.com/bdmac/strong_password/issues/12
- mail gem with dependency on mime-types

**Comment by sergey-alekseev** [comment]
@stereobooster interesting points. I didn't quite get why you call gems "useless". They do their job.  
It looks like  
- https://github.com/RubyMoney/money/issues/688  
- https://github.com/rack/rack-contrib/pull/114  

contain nice optimizations of not critical memory issues.  

If you can attach a benchmark and other proofs of memory bloat in https://github.com/bdmac/strong_password/issues/12 then it can be included into the list for sure.

**Comment by stereobooster** [comment]
- rack/rack-contrib contained git-version-bump before version 1.5 (as runtime dependency), which took 9mb of memory for no reason.
- RubyMoney/money contained unaccent gem, which is used very rarely and it took 4mb of memory
-  bdmac/strong_password loads database of week password in memory as array of strings, this is obviously not optimal way to do this

Those all are not critical issues, they are just bad practices.

**Comment by sergey-alekseev** [comment]
@stereobooster in my view those are minor problems which don't grow with data/load growth and take a fixed amount of memory. Correct me if I'm wrong. 4-9 MB of memory is nothing in comparison with GBs of wasted RAM while a leak or a bloat is introduced. Feel free to create more issues and PRs if you notice such behavior.

**Comment by DanielVartanov** [comment]
As for me, I am interested in an *infinite* growth of memory usage which sooner or later will break *any* memory limit. Static waste of time, even if large ones, are nowhere near as dangerous as infinite ones.
