### ISSUE TITLE
Maybe add axlsx to the list?

### ISSUE THREAD

**Issue by srpouyet** [ASoftCo/leaky-gems#6]
I'm not sure if this axlsx [issue](https://github.com/randym/axlsx/issues/276) qualifies as a memory leak, but we've had some issues (crashing workers) with this gem due to the huge amount of memory it is known to use with large datasets. So maybe you'll want to add it?

**Comment by sergey-alekseev** [comment]
@srpouyet thanks for bringing the attention. 
I need a confirmation the gem is actually **leaky** to add it to the list. After reading [the issue](https://github.com/randym/axlsx/issues/276) you mentioned it becomes clear the gem may take a lot of memory with large datasets. But can you confirm it does not release the memory?
