### ISSUE TITLE
How do you verify the submitted gems to be truly leaky?

### ISSUE THREAD

**Issue by kenn** [ASoftCo/leaky-gems#8]
I had an impression that the list is fairly incomplete when I couldn't find [rmagick](https://github.com/rmagick/rmagick) in it, which is the canonical gem when we talk about colossal leaks, but then I realized that proving there's a memory leak in a gem is not easy, particularly when we have to narrow down to versions.

Do we have a methodological way to prove or disprove if there's a memory leak? Otherwise we'll end up with just blindly trusting the person who sends a pull request.

**Comment by ivan-kolmychek** [comment]
> Do we have a methodological way to prove or disprove if there's a memory leak?

From what I see, link to proof (usually it's a bug in the bugtracker of a gem, I guess) is required.

**Comment by kenn** [comment]
> From what I see, link to proof (usually it's a bug in the bugtracker of a gem, I guess) is required.

Ah, OK. But I think the hard part is proving if it's truly "fixed", even when the poster says so. When there's a leak, chances are, there are other leak points. I just hoped there was a simple way to find that out...

**Comment by sergey-alekseev** [comment]
@kenn can you add rmagick with versions specified and a link? The list contains only [**known**](https://github.com/ASoftCo/leaky-gems/commit/6f5147695ea74770d537a402aa00ce0b0c55797d) memory leaks that proved and confirmed to be fixed.
@ivan-kolmychek thanks for the help.

**Comment by kenn** [comment]
Unfortunately I don't know the current state of the gem as I stopped using it. It had never been fixed when I was using and everyone restarted the processes periodically. I hope someone in the know would show up and add more details.
